config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :restaurants do
    resources :reviews
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  validates :name, presence: true
  validates :phone_number, presence: true
  validates :address, presence: true
  validates :category, presence: true, inclusion: { in: %w(chinese italian japanese belgian french) }

  has_many :reviews, dependent: :destroy
end

app/models/review.rb
class Review < ApplicationRecord
  validates :content, presence: true
  validates :rating, presence: true, inclusion: { :in => (0..5) }, numericality: true

  belongs_to :restaurant
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController

  before_action :set_restaurant, only: [:show, :edit, :update, :destroy]

  def index
    @restaurants = Restaurant.all
  end

  def show
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      redirect_to @restaurant
    else
      render :new
    end
  end

  def update
    if @restaurant.update(restaurant_params)
      redirect_to restaurant_path(@restaurant)
    else
      render :edit
    end
  end

  def edit
  end

  def destroy
    @restaurant.destroy
    redirect_to restaurants_path
  end

  private

  def set_restaurant
    @restaurant = Restaurant.find(params[:id])
  end

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :phone_number, :category)
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review.restaurant = @restaurant
    if @review.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new
    end
  end

  private

  def review_params
    params.require(:review).permit(:content, :rating)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/restaurants/_form.html.erb
<%= simple_form_for(@restaurant) do |f| %>
  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.input :phone_number %>
  <%= f.input :category, selected: "chinese", collection: %w(chinese italian japanese belgian french) %>

  <%= f.button :submit %>
<% end %>

app/views/restaurants/edit.html.erb
<h1>Edit</h1>

<%= render 'form', restaurant: @restaurant %>

<p><%= link_to "Home", restaurants_path %></p>

app/views/restaurants/index.html.erb
<h1>List of Restaurants</h1>
  <hr>

<% @restaurants.each do |restaurant| %>
  <%= link_to restaurant.name, restaurant %>
  <%= restaurant.address %>
  <%= restaurant.phone_number %>
  <%= restaurant.category.capitalize %>
  <%= link_to 'Edit', edit_restaurant_path(restaurant) %>
  <%= link_to 'Delete', restaurant, method: :delete, data: { confirm: 'Are you sure?' } %>
  <hr>
<% end %>

<%= link_to "New", new_restaurant_path %>

app/views/restaurants/new.html.erb
<h1>New</h1>

<%= render 'form', restaurant: @restaurant %>

<p><%= link_to "Home", restaurants_path %></p>

app/views/restaurants/show.html.erb
<h1><%= @restaurant.name %></h1>
<%= @restaurant.address %><br>
<%= @restaurant.phone_number %><br>
<%= @restaurant.category.capitalize %>

<h1>Reviews</h1>
<% @restaurant.reviews.each do |review| %>
  <%= review.content %>
  <%= review.rating %>
  <hr>
<% end %>

<p><%= link_to "Add review", new_restaurant_review_path(@restaurant) %></p>
<p><%= link_to "Home", restaurants_path %></p>

app/views/reviews/new.html.erb
<h1>Write a review</h1>

<%= simple_form_for [@restaurant, @review] do |f| %>
  <%= f.input :content %>
  <%= f.input :rating %>
  <%= f.submit "Post" %>
<% end %>